/**
 * Recommendation outcome tracking — closes the feedback loop on the /analysis
 * signals.
 *
 * The `recommendation` table has always carried `price_at_{30,90,365}d`,
 * `return_pct_*` and `hit_*` columns, but nothing in this repo ever wrote them,
 * and the analysis page's own Combined signals were never persisted at all. So
 * no tab could answer "does ACCUMULATE actually beat AVOID?" — every weight in
 * the app (0.60/0.40 Combined, AI Analyst's 26/24/18/14/10/8, AI Screening's
 * six) was an unvalidated guess.
 *
 * Three parts, in order:
 *   1. `recordSignals`  — persist today's signals so there is something to score
 *   2. `evaluateDueOutcomes` — backfill the horizon columns once each matures
 *   3. `getSignalAccuracy`   — realized hit-rate per signal label
 *
 * Price-unit note: this app stores prices inconsistently (technical_snapshot is
 * in thousands of VND, live quotes are full VND — see `priceKToVnd`). Both the
 * entry and exit price here come from the same `price_daily.close_px` column,
 * so `returnPct` is a ratio of two like-scaled numbers and is unit-independent
 * by construction. Do not "fix" this by routing either side through
 * `toVndPrice` — that would reintroduce the trap.
 */

import { prisma } from "@/lib/prisma";
import { withDbRetry } from "@/lib/prisma-query";
import { isPersistenceEnabled } from "@/lib/persistence";

export const OUTCOME_HORIZONS = [30, 90, 365] as const;
export type OutcomeHorizon = (typeof OUTCOME_HORIZONS)[number];

/** Default source tag for signals generated by the /analysis Combined tab. */
export const ANALYSIS_SOURCE = "analysis";

/**
 * Trading days are sparse (weekends, Tet). When looking for the price at
 * horizon end we accept the first session at or after the target date, within
 * this many calendar days, rather than demanding an exact match.
 */
const SESSION_TOLERANCE_DAYS = 10;

const HORIZON_FIELDS = {
  30: { price: "priceAt30d", ret: "returnPct30d", hit: "hit30d", evaluated: "evaluatedDate30d" },
  90: { price: "priceAt90d", ret: "returnPct90d", hit: "hit90d", evaluated: "evaluatedDate90d" },
  365: { price: "priceAt365d", ret: "returnPct365d", hit: "hit365d", evaluated: "evaluatedDate365d" },
} as const satisfies Record<OutcomeHorizon, { price: string; ret: string; hit: string; evaluated: string }>;

export type SignalDirection = "bullish" | "bearish" | "neutral";

/**
 * Map a signal label to a testable direction.
 *
 * Only directional calls can be scored right/wrong. HOLD and WATCH express "no
 * action", so they get `neutral` — their return is still recorded, but `hit`
 * stays NULL and they are excluded from hit-rate denominators. Scoring a HOLD
 * as a "miss" because the stock rose would be measuring the wrong thing.
 */
export function signalDirection(recommendation: string): SignalDirection {
  const u = recommendation.toUpperCase();
  if (u.includes("ACCUMULATE") || u.includes("BUY")) return "bullish";
  if (u.includes("SELL") || u.includes("AVOID") || u.includes("TRIM")) return "bearish";
  return "neutral";
}

function startOfUtcDay(date: Date): Date {
  return new Date(
    Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()),
  );
}

function addDays(date: Date, days: number): Date {
  const d = new Date(date);
  d.setUTCDate(d.getUTCDate() + days);
  return d;
}

// ---------------------------------------------------------------------------
// 1. Record
// ---------------------------------------------------------------------------

export type SignalToRecord = {
  symbol: string;
  name?: string | null;
  recommendation: string;
  technicalScore: number;
  fundamentalScore: number;
  combinedScore: number;
};

/**
 * Persist a day's signals. Idempotent per (symbol, source, date) via the
 * existing `uq_recommendation_unique` constraint, so re-running on the same day
 * refreshes rather than duplicating.
 *
 * Rows whose entry price can't be resolved from `price_daily` are skipped, not
 * stored with a zero price — a zero entry price would produce an infinite
 * return at evaluation time and silently poison the hit-rate.
 */
export async function recordSignals(
  signals: SignalToRecord[],
  source: string = ANALYSIS_SOURCE,
  asOf: Date = new Date(),
): Promise<{ recorded: number; skipped: string[] }> {
  if (!isPersistenceEnabled() || signals.length === 0) {
    return { recorded: 0, skipped: signals.map((s) => s.symbol) };
  }

  const recommendationDate = startOfUtcDay(asOf);
  const symbols = [...new Set(signals.map((s) => s.symbol.toUpperCase()))];

  // Latest close at or before the recommendation date, per symbol.
  const priceRows = await withDbRetry(
    () =>
      prisma.priceDaily.findMany({
        where: {
          symbol: { in: symbols },
          tradeDate: {
            gte: addDays(recommendationDate, -SESSION_TOLERANCE_DAYS),
            lte: recommendationDate,
          },
          closePx: { gt: 0 },
        },
        orderBy: { tradeDate: "desc" },
        select: { symbol: true, closePx: true },
      }),
    "outcome-entry-prices",
    0,
  );

  const entryPrice = new Map<string, number>();
  for (const row of priceRows) {
    const sym = row.symbol.toUpperCase();
    if (!entryPrice.has(sym) && row.closePx != null) {
      entryPrice.set(sym, row.closePx);
    }
  }

  const skipped: string[] = [];
  let recorded = 0;

  for (const signal of signals) {
    const sym = signal.symbol.toUpperCase();
    const price = entryPrice.get(sym);
    if (price == null || price <= 0) {
      skipped.push(sym);
      continue;
    }

    try {
      await withDbRetry(
        () =>
          prisma.recommendation.upsert({
            where: {
              symbol_source_recommendationDate: {
                symbol: sym,
                source,
                recommendationDate,
              },
            },
            create: {
              symbol: sym,
              name: signal.name ?? null,
              source,
              recommendation: signal.recommendation,
              priceAtRecommendation: price,
              technicalScore: Math.round(signal.technicalScore),
              fundamentalScore: Math.round(signal.fundamentalScore),
              combinedScore: Math.round(signal.combinedScore),
              recommendationDate,
            },
            update: {
              recommendation: signal.recommendation,
              priceAtRecommendation: price,
              technicalScore: Math.round(signal.technicalScore),
              fundamentalScore: Math.round(signal.fundamentalScore),
              combinedScore: Math.round(signal.combinedScore),
            },
          }),
        "outcome-record",
        0,
      );
      recorded += 1;
    } catch {
      skipped.push(sym);
    }
  }

  return { recorded, skipped };
}

// ---------------------------------------------------------------------------
// 2. Evaluate
// ---------------------------------------------------------------------------

export type EvaluationSummary = {
  evaluatedAt: string;
  byHorizon: { horizon: OutcomeHorizon; evaluated: number; pending: number }[];
  totalEvaluated: number;
};

/**
 * Backfill matured horizons. A row is due when `recommendationDate + horizon`
 * has passed and its `evaluated_date_*` is still NULL.
 *
 * Rows still inside their horizon are left alone — this never guesses at an
 * unfinished outcome, and never re-scores one already written, so it is safe to
 * run on any schedule.
 */
export async function evaluateDueOutcomes(
  asOf: Date = new Date(),
): Promise<EvaluationSummary> {
  const today = startOfUtcDay(asOf);
  const byHorizon: EvaluationSummary["byHorizon"] = [];
  let totalEvaluated = 0;

  if (!isPersistenceEnabled()) {
    return {
      evaluatedAt: today.toISOString(),
      byHorizon: OUTCOME_HORIZONS.map((h) => ({ horizon: h, evaluated: 0, pending: 0 })),
      totalEvaluated: 0,
    };
  }

  for (const horizon of OUTCOME_HORIZONS) {
    const fields = HORIZON_FIELDS[horizon];
    const cutoff = addDays(today, -horizon);

    const due = await withDbRetry(
      () =>
        prisma.recommendation.findMany({
          where: {
            recommendationDate: { lte: cutoff },
            [fields.evaluated]: null,
          },
          select: {
            id: true,
            symbol: true,
            source: true,
            recommendation: true,
            recommendationDate: true,
            priceAtRecommendation: true,
          },
          orderBy: { recommendationDate: "asc" },
        }),
      `outcome-due-${horizon}`,
      0,
    );

    let evaluated = 0;

    for (const row of due) {
      if (row.priceAtRecommendation <= 0) continue;

      const target = addDays(startOfUtcDay(row.recommendationDate), horizon);
      const exit = await withDbRetry(
        () =>
          prisma.priceDaily.findFirst({
            where: {
              symbol: row.symbol.toUpperCase(),
              tradeDate: {
                gte: target,
                lte: addDays(target, SESSION_TOLERANCE_DAYS),
              },
              closePx: { gt: 0 },
            },
            orderBy: { tradeDate: "asc" },
            select: { closePx: true, tradeDate: true },
          }),
        `outcome-exit-${horizon}`,
        0,
      );

      // No session found in the tolerance window — leave unevaluated so a later
      // run can pick it up once price_daily backfills, rather than writing a
      // fabricated outcome.
      if (!exit?.closePx) continue;

      const returnPct =
        ((exit.closePx - row.priceAtRecommendation) / row.priceAtRecommendation) * 100;
      const direction = signalDirection(row.recommendation);
      const hit =
        direction === "bullish"
          ? returnPct > 0
          : direction === "bearish"
            ? returnPct < 0
            : null;

      await withDbRetry(
        () =>
          prisma.recommendation.update({
            where: { id: row.id },
            data: {
              [fields.price]: exit.closePx,
              [fields.ret]: Math.round(returnPct * 100) / 100,
              [fields.hit]: hit,
              [fields.evaluated]: startOfUtcDay(exit.tradeDate),
            },
          }),
        `outcome-write-${horizon}`,
        0,
      );
      evaluated += 1;
    }

    byHorizon.push({ horizon, evaluated, pending: due.length - evaluated });
    totalEvaluated += evaluated;
  }

  return { evaluatedAt: today.toISOString(), byHorizon, totalEvaluated };
}

// ---------------------------------------------------------------------------
// 3. Report
// ---------------------------------------------------------------------------

export type SignalAccuracyRow = {
  recommendation: string;
  direction: SignalDirection;
  horizon: OutcomeHorizon;
  /** Directional calls only — neutral signals are excluded from this count. */
  scored: number;
  hits: number;
  hitRatePct: number | null;
  /** Mean return across ALL evaluated rows, including neutral ones. */
  sampleSize: number;
  avgReturnPct: number | null;
};

export type SignalAccuracyReport = {
  generatedAt: string;
  /** True when nothing has matured yet — the UI must not render 0% as a result. */
  isEmpty: boolean;
  totalRecorded: number;
  oldestRecordedAt: string | null;
  rows: SignalAccuracyRow[];
};

/**
 * Realized accuracy per signal label and horizon.
 *
 * `hitRatePct` is null (not 0) when no directional calls have matured for that
 * bucket — an unmeasured signal and a signal that has never been right are very
 * different claims, and collapsing them to 0% would be the same class of bug as
 * scoring a data-less stock as 50/"Fair".
 */
export async function getSignalAccuracy(
  source: string = ANALYSIS_SOURCE,
): Promise<SignalAccuracyReport> {
  const generatedAt = new Date().toISOString();
  const empty: SignalAccuracyReport = {
    generatedAt,
    isEmpty: true,
    totalRecorded: 0,
    oldestRecordedAt: null,
    rows: [],
  };

  if (!isPersistenceEnabled()) return empty;

  try {
    const rows = await withDbRetry(
      () =>
        prisma.recommendation.findMany({
          where: { source },
          select: {
            recommendation: true,
            recommendationDate: true,
            returnPct30d: true,
            hit30d: true,
            returnPct90d: true,
            hit90d: true,
            returnPct365d: true,
            hit365d: true,
          },
        }),
      "outcome-accuracy",
      0,
    );

    if (!rows.length) return empty;

    const oldest = rows.reduce<Date | null>((min, r) => {
      const d = r.recommendationDate;
      return min == null || d < min ? d : min;
    }, null);

    type Bucket = { scored: number; hits: number; returns: number[] };
    const buckets = new Map<string, Bucket>();
    const key = (rec: string, h: OutcomeHorizon) => `${rec}::${h}`;

    for (const row of rows) {
      const perHorizon: { horizon: OutcomeHorizon; ret: number | null; hit: boolean | null }[] = [
        { horizon: 30, ret: row.returnPct30d, hit: row.hit30d },
        { horizon: 90, ret: row.returnPct90d, hit: row.hit90d },
        { horizon: 365, ret: row.returnPct365d, hit: row.hit365d },
      ];

      for (const { horizon, ret, hit } of perHorizon) {
        if (ret == null) continue; // not yet evaluated
        const k = key(row.recommendation, horizon);
        const bucket = buckets.get(k) ?? { scored: 0, hits: 0, returns: [] };
        bucket.returns.push(ret);
        if (hit != null) {
          bucket.scored += 1;
          if (hit) bucket.hits += 1;
        }
        buckets.set(k, bucket);
      }
    }

    const out: SignalAccuracyRow[] = [];
    for (const [k, bucket] of buckets) {
      const [recommendation, horizonStr] = k.split("::");
      const horizon = Number(horizonStr) as OutcomeHorizon;
      const avg =
        bucket.returns.length > 0
          ? bucket.returns.reduce((a, b) => a + b, 0) / bucket.returns.length
          : null;
      out.push({
        recommendation,
        direction: signalDirection(recommendation),
        horizon,
        scored: bucket.scored,
        hits: bucket.hits,
        hitRatePct:
          bucket.scored > 0 ? Math.round((bucket.hits / bucket.scored) * 1000) / 10 : null,
        sampleSize: bucket.returns.length,
        avgReturnPct: avg != null ? Math.round(avg * 100) / 100 : null,
      });
    }

    out.sort((a, b) => a.horizon - b.horizon || a.recommendation.localeCompare(b.recommendation));

    return {
      generatedAt,
      isEmpty: out.length === 0,
      totalRecorded: rows.length,
      oldestRecordedAt: oldest ? oldest.toISOString() : null,
      rows: out,
    };
  } catch {
    return empty;
  }
}
